# -*- coding: utf-8 -*-
"""EvaluatingRegressionModel_RSquared.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lzs5-5RIHium2QMiNLPVe6BvKwYMeYxJ

Import Libraries
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

"""Load dataset from local directory"""

from google.colab import files
uploaded = files.upload()

"""Load dataset"""

dataset = pd.read_csv('dataset1.csv')

"""Summarize dataset"""

print(dataset.shape)
print(dataset.head(5))

"""Visaulize  dataset"""

plt.xlabel('area')
plt.ylabel('price')
plt.scatter(dataset.area,dataset.price,color = 'red', marker='*')

"""Segregate dataset into input X and output Y"""

x = dataset.drop('price',axis='columns')
x

y= dataset.price
y

"""Split to test model"""

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=0)

"""Training dataset using Linear regression"""

model =  LinearRegression()
model.fit(x_train,y_train)

"""Visualising Linear regression result"""

plt.scatter(x,y,color='black',marker='*')
plt.plot(x,model.predict(x))
plt.title("Linear Regression")
plt.xlabel('area')
plt.ylabel('price')

"""R-squared score"""

rsq = model.score(x_test,y_test)
print(rsq)

"""Adjusted r2"""



n=len(dataset)
p=len(dataset.columns)-1
adjr=1-(1-rsq)*(n-1)/(n-p-1)
print(adjr)

"""Prediction"""

x = 8760
LandAreainSqft=[[x]]
pridictedresult = model.predict(LandAreainSqft)
print(pridictedresult)

